---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: challenge-pv
  namespace: java-app
spec:
  capacity:
    storage: 100Mi  # Specify the storage size
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/challenge-pv  # Path on the host where data will be stored
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: challenge-pvc
  namespace: java-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # Request the same size as the PV
  storageClassName: manual