# Use the official OpenJDK image as a base for the build stage
FROM openjdk:21-jdk-slim AS build

# Set the working directory
WORKDIR /app

# Copy the Gradle wrapper and build files
COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./

# Copy project files
COPY src src

# Grant execution permission to gradlew
RUN chmod +x gradlew

# Mount temp secret
RUN --mount=type=secret,id=my_api_key \
 export API_KEY=$(cat /run/secrets/my_api_key) && \
 echo $API_KEY && ./gradlew build --no-daemon

# Create a new stage to minimize the final image size
FROM gcr.io/distroless/java21-debian12 AS runtime

# Set the working directory
WORKDIR /app

# Copy the built JAR file from the previous stage
COPY --from=build /app/build/libs/challenge-0.0.1-SNAPSHOT.jar app.jar

# Set the entry point for the Docker container
ENTRYPOINT ["java", "-jar", "app.jar"]

# Expose the port the application will run on
EXPOSE 8080